---
title: "BDC_Visualization"
author: "Lucia Darrow"
date: "2/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(data.table)
library(magrittr)
library(ggplot2)
library(visdat)

library(ggforce)
library(ggtext)
library(gganimate)
library(extrafont)
library(showtext)
library(magick)
```

```{r font}
# Process to add new fonts
# font_add_google("Ultra", "Ultra")
# font_add_google("Roboto", "Roboto")
# font_add_google("Alfa Slab One", "Alfa Slab One")
# font_add_google("Open Sans Condensed", "Open Sans Condensed", regular.wt = 300)
# 
# # Load font from the current search path into showtext
# 
# # Check the current search path for fonts
# font_paths()    
# #> [1] "C:\\Windows\\Fonts"
# 
# # List available font files in the search path
# font_files()    
# #>   [1] "AcadEref.ttf"                                
# #>   [2] "AGENCYB.TTF"                           
# #> [428] "pala.ttf"                                    
# #> [429] "palab.ttf"                                   
# #> [430] "palabi.ttf"                                  
# #> [431] "palai.ttf"
# 
# # syntax: font_add(family = "<family_name>", regular = "/path/to/font/file")
# fontsView <- font_files()
# font_add("OpenSans", "OpenSans-Regular.ttf")
# font_add("Roboto", "RobotoCondensed-Regular.ttf")
# 
# font_families()
# #> [1] "sans"         "serif"        "mono"         "wqy-microhei"
# #> [5] "Montserrat"   "Roboto"       "Palatino"
# 
# ## automatically use showtext for new devices
showtext_auto()

```

```{r readData}
# Read in the hackathon dataset
BDC_womens <- fread("../data/BDC_hackathon_womens.csv")
BDC_pass <- fread("../data/BDC_womens_PassStrategy.csv")

```

```{r}
BDC_womens %<>% 
  mutate(absXdist = abs(X.Coordinate.2 - X.Coordinate),
         absYdist = abs(Y.Coordinate.2 - Y.Coordinate), 
         strategy = ifelse(absYdist > absXdist, "EW", "NS")) 

```

```{r plots}

# Let's plot the data on the rink, recalling this is from the perspective of the eventing team
# All data
BDC_womens %>%
ggplot(aes(x = X.Coordinate, y = Y.Coordinate)) +
  labs(title = "") +
  geom_point(alpha = 0.1, size = 0.2) +
  xlim(0, 200) + ylim(0, 85) +
  geom_density_2d_filled(alpha = 0.35, show.legend = FALSE) +
  theme_void()

# Location of eventing team in dump in/out scenario
BDC_womens %>% filter(Event == "Dump In/Out") %>%
ggplot(aes(x = X.Coordinate, y = Y.Coordinate)) +
  labs(title = "") +
  geom_point(alpha = 0.1, size = 0.2) +
  xlim(0, 200) + ylim(0, 85) +
  geom_density_2d_filled(alpha = 0.35, show.legend = FALSE) +
  theme_void()

# Location of eventing team in shot scenario
BDC_womens %>% filter(Event == "Shot") %>%
ggplot(aes(x = X.Coordinate, y = Y.Coordinate)) +
  labs(title = "") +
  geom_point(alpha = 0.1, size = 0.2) +
  xlim(0, 200) + ylim(0, 85) +
  geom_density_2d_filled(alpha = 0.35, show.legend = FALSE) +
  theme_void()


coords <- data.frame(X = c(168, 197, 6),
                     Y = c(1, 26, 64))



BDC_womens$rink <- startsWith(BDC_womens$Home.Team, "Olympic")

BDC_womens %>%
  ggplot(aes(x = X.Coordinate, y = Y.Coordinate, color = rink), alpha = 0.5) +
  labs(title = "") +
  geom_point(alpha = 0.1, size = 0.2) +
  xlim(0, 200) + ylim(0, 85) +
  geom_point()
  # geom_density_2d_filled(alpha = 0.35, show.legend = FALSE) +
  # theme_void()

```



```{r}

BDC_womens %>% group_by(Event, Detail.1, Detail.2, Detail.3, Detail.4) %>%
  summarise(n()) -> BDC_womens_grouped

```

```{r timeline}
BDC_womens_timeline <- BDC_womens %>% filter(game_date == "2018-02-11")

library(lubridate)
BDC_womens_timeline$Clock %<>% ms() 
BDC_womens_timeline$Clock[BDC_womens_timeline$Period == 2, ] = BDC_womens_timeline$Clock[BDC_womens_timeline$Period == 2, ] + minutes(20)
BDC_womens_timeline$Clock[BDC_womens_timeline$Period == 3, ] = BDC_womens_timeline$Clock[BDC_womens_timeline$Period == 3, ] + minutes(40)

BDC_womens_timeline %>%
  select(Clock, X.Coordinate) %>%
  ggplot() +
  geom_point(aes(x=Clock, y=X.Coordinate)) +
  scale_x_datetime(date_breaks = "1 hour",
                       date_labels = "%I:%M %p")

```

```{r}

# https://thewincolumn.ca/2021/01/15/r-tutorial-creating-an-nhl-rink-using-the-tidyverse/
library(tidyverse)
library(ggforce)

# Setting up colour values
NHL_red <- "#FFCCD8" # Use #C8102E for original red in the rules, #FFE6EB for lighter hue
NHL_blue <- "#CCE1FF" # Use #0033A0 for original blue in the rules, #E6EFFF for lighter hue
NHL_light_blue <- "#CCF5FF" # Use #41B6E6 for original crease blue in the rules, #E6F9FF for lighter hue

nhl_rink_plot <- function () {
  
  # Plotting an NHL rink completely following the NHL rule book:
  # https://cms.nhl.bamgrid.com/images/assets/binary/308893668/binary-file/file.pdf
  # Line widths, lengths, colours, all followed as closely as possible
  
ggplot() +
  
  # Faceoff circles
  geom_circle(aes(x0 = 0, y0 = 0, r = 15), colour = NHL_blue, size = 2 / 12) + # Centre
  geom_circle(aes(x0 = 69, y0 = 22, r = 15), colour = NHL_red, size = 2 / 12) + # Top-Right
  geom_circle(aes(x0 = 69, y0 = -22, r = 15), colour = NHL_red, size = 2 / 12) + # Bottom-Right
  geom_circle(aes(x0 = -69, y0 = 22, r = 15), colour = NHL_red, size = 2 / 12) + # Top-Left
  geom_circle(aes(x0 = -69, y0 = -22, r = 15), colour = NHL_red, size = 2 / 12) + # Bottom-Left
  
  # Hash marks in T-R/B-R/T-L/B-R order, groups of four
  geom_tile(aes(x = 66.125, y = 37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = 66.125, y = 6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = 71.875, y = 37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = 71.875, y = 6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = 66.125, y = -37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = 66.125, y = -6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = 71.875, y = -37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = 71.875, y = -6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -66.125, y = 37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -66.125, y = 6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -71.875, y = 37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -71.875, y = 6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -66.125, y = -37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -66.125, y = -6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -71.875, y = -37.77, width = 2 / 12, height = 2), fill = NHL_red) +
  geom_tile(aes(x = -71.875, y = -6.23, width = 2 / 12, height = 2), fill = NHL_red) +
  
  # Centre line
  geom_tile(aes(x = 0, y = 0, width = 1, height = 85), fill = NHL_red) + # Centre line

  # Faceoff dots - Plot AFTER centre lines for centre ice circle to show up above
  geom_circle(aes(x0 = 0, y0 = 0, r = 6 / 12), colour = "#FF99B4", fill = "#FF99B4", size = 0) + # Centre dot with unique red
  geom_circle(aes(x0 = 69, y0 = 22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Top-Right
  geom_circle(aes(x0 = 69, y0 = -22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Bottom-Right
  geom_circle(aes(x0 = -69, y0 = 22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Top-Left
  geom_circle(aes(x0 = -69, y0 = -22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Bottom-Left
  
  geom_circle(aes(x0 = 20.5, y0 = 22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Neutral Top-Right
  geom_circle(aes(x0 = 20.5, y0 = -22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Neutral Bottom-Right
  geom_circle(aes(x0 = -20.5, y0 = 22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Neutral Top-Left
  geom_circle(aes(x0 = -20.5, y0 = -22, r = 1), colour = NHL_red, fill = NHL_red, size = 0) + # Neutral Bottom-Left
  
  # Ells surrounding faceoff dots
  geom_tile(aes(x = 65, y = 22.83, width = 4, height = 2 / 12), fill = NHL_red) + # Top-Right
  geom_tile(aes(x = 73, y = 22.83, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = 65, y = 21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = 73, y = 21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = 66.92, y = 24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = 71.08, y = 24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = 66.92, y = 19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = 71.08, y = 19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  
  geom_tile(aes(x = 65, y = -22.83, width = 4, height = 2 / 12), fill = NHL_red) + # Bottom-Right
  geom_tile(aes(x = 73, y = -22.83, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = 65, y = -21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = 73, y = -21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = 66.92, y = -24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = 71.08, y = -24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = 66.92, y = -19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = 71.08, y = -19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  
  geom_tile(aes(x = -65, y = 22.83, width = 4, height = 2 / 12), fill = NHL_red) + # Top-Left
  geom_tile(aes(x = -73, y = 22.83, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = -65, y = 21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = -73, y = 21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = -66.92, y = 24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = -71.08, y = 24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = -66.92, y = 19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = -71.08, y = 19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  
  geom_tile(aes(x = -65, y = -22.83, width = 4, height = 2 / 12), fill = NHL_red) + # Bottom-Left
  geom_tile(aes(x = -73, y = -22.83, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = -65, y = -21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = -73, y = -21.17, width = 4, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = -66.92, y = -24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = -71.08, y = -24.25, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = -66.92, y = -19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  geom_tile(aes(x = -71.08, y = -19.75, width = 2 / 12, height = 3), fill = NHL_red) +
  
  # Referee crease
  geom_arc(aes(x0 = 0, y0 = -42.5, start = -pi / 2, end = pi / 2, r = 10), colour = NHL_red) +
  
  # Left goalie crease
  geom_tile(aes(x = -86.75, y = 0, width = 4.5, height = 8), fill = NHL_light_blue) +
  geom_arc_bar(aes(x0 = -89, y0 = 0, start = atan(4.5/4) - 0.01, end = pi - atan(4.5 / 4) + 0.01, r0 = 4, r = 6), fill = NHL_light_blue, colour = NHL_light_blue, size = 1 / 12) + # manually adjusted arc
  geom_tile(aes(x = -86.75, y = -4, width = 4.5, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = -86.75, y = 4, width = 4.5, height = 2 / 12), fill = NHL_red) +
  geom_arc(aes(x0 = -89, y0 = 0, start = atan(4.5/4) - 0.01, end = pi - atan(4.5 / 4) + 0.01, r = 6), colour = NHL_red, size = 2 / 12) + # manually adjusted arc
  geom_tile(aes(x = -85, y = 3.75, width = 2 / 12, height = 0.42), fill = NHL_red) +
  geom_tile(aes(x = -85, y = -3.75, width = 2 / 12, height = 0.42), fill = NHL_red) +
  
  # Right goalie crease
  geom_tile(aes(x = 86.75, y = 0, width = 4.5, height = 8), fill = NHL_light_blue) +
  geom_arc_bar(aes(x0 = 89, y0 = 0, start = -atan(4.5/4) + 0.01, end = -pi + atan(4.5 / 4) - 0.01, r0 = 4, r = 6), fill = NHL_light_blue, colour = NHL_light_blue, size = 1 / 12) + # manually adjusted arc
  geom_tile(aes(x = 86.75, y = -4, width = 4.5, height = 2 / 12), fill = NHL_red) +
  geom_tile(aes(x = 86.75, y = 4, width = 4.5, height = 2 / 12), fill = NHL_red) +
  geom_arc(aes(x0 = 89, y0 = 0, start = -atan(4.5/4) + 0.01, end = -pi + atan(4.5 / 4) - 0.01, r = 6), colour = NHL_red, size = 2 / 12) + # manually adjusted arc
  geom_tile(aes(x = 85, y = 3.75, width = 2 / 12, height = 0.42), fill = NHL_red) +
  geom_tile(aes(x = 85, y = -3.75, width = 2 / 12, height = 0.42), fill = NHL_red) +
  
  # Goalie nets placed as rectangles
  geom_tile(aes(x = -90.67, y = 0, width = 3.33, height = 6), fill = "#E5E5E3") + # Left # with grey fills
  geom_tile(aes(x = 90.67, y = 0, width = 3.33, height = 6), fill = "#E5E5E3") + # Right
  
  # Trapezoids
  geom_polygon(aes(x = c(-100, -100, -89, -89), y = c(10.92, 11.08, 7.08, 6.92)), fill = NHL_red) + # Left
  geom_polygon(aes(x = c(-100, -100, -89, -89), y = c(-10.92, -11.08, -7.08, -6.92)), fill = NHL_red) + # Left
  geom_polygon(aes(x = c(100, 100, 89, 89), y = c(10.92, 11.08, 7.08, 6.92)), fill = NHL_red) + # Right
  geom_polygon(aes(x = c(100, 100, 89, 89), y = c(-10.92, -11.08, -7.08, -6.92)), fill = NHL_red) + # Right
  
  # Lines
  geom_tile(aes(x = -25.5, y = 0, width = 1, height = 85), fill = NHL_blue) + # Left Blue line
  geom_tile(aes(x = 25.5, y = 0, width = 1, height = 85),  fill = NHL_blue) + # Right Blue line
  geom_tile(aes(x = -89, y = 0, width = 2 / 12, height = 73.50), fill = NHL_red) + # Left goal line (73.5 value is rounded from finding intersect of goal line and board radius)
  geom_tile(aes(x = 89, y = 0, width = 2 / 12, height = 73.50), fill = NHL_red) + # Right goal line
  
  # Borders as line segments - plotted last to cover up line ends, etc.
  geom_line(aes(x = c(-72, 72), y = c(42.5, 42.5))) + # Top
  geom_line(aes(x = c(-72, 72), y = c(-42.5, -42.5))) + # Bottom
  geom_line(aes(x = c(-100, -100), y = c(-14.5, 14.5))) + # Left
  geom_line(aes(x = c(100, 100), y = c(-14.5, 14.5))) + # Right
  geom_arc(aes(x0 = 72, y0 = 14.5, start = pi / 2, end = 0, r = 28)) + # Top-Right
  geom_arc(aes(x0 = 72, y0 = -14.5, start = pi, end =  pi / 2, r = 28)) + # Bottom-Right
  geom_arc(aes(x0 = -72, y0 = 14.5, start = - pi / 2, end = 0, r = 28)) + # Top-Left
  geom_arc(aes(x0 = -72, y0 = -14.5, start = pi, end =  3 * pi / 2, r = 28)) + # Bottom-Left
  
  # Fixed scale for the coordinate system  
  coord_fixed()
}

# theme_void() # include this for a blank plot, but likely easier to include in ggplot2 function in main code to control layering

nhl_rink_plot() + theme_void()

```

```{r}
# 0 - 200
# -100 - 100
BDC_womens$X.Coordinate.Plot <- BDC_womens$X.Coordinate - 100

# 0 - 85
# -42.5 - 42.5
BDC_womens$Y.Coordinate.Plot <- BDC_womens$Y.Coordinate - 42.5

nhl_rink_plot() + geom_point(BDC_womens, mapping = aes(x = X.Coordinate.Plot, y = Y.Coordinate.Plot), alpha = 0.1) + theme_void()

# Play, Incomplete Play
BDC_pass_filter <- BDC_pass %>% filter(Event %in% c("Play", "Incomplete Play")) 
  
BDC_pass_filter$X.Coordinate.Plot <- BDC_pass_filter$X.Coordinate - 100
BDC_pass_filter$X.Coordinate.Plot2 <- BDC_pass_filter$X.Coordinate.2 - 100

# 0 - 85
# -42.5 - 42.5
BDC_pass_filter$Y.Coordinate.Plot <- BDC_pass_filter$Y.Coordinate - 42.5
BDC_pass_filter$Y.Coordinate.Plot2 <- BDC_pass_filter$Y.Coordinate.2 - 42.5

nhl_rink_plot() + geom_point(BDC_pass_filter, mapping = aes(x = X.Coordinate.Plot, y = Y.Coordinate.Plot, fill = "green"), alpha = 0.1)  +
  geom_point(BDC_pass_filter, mapping = aes(x = X.Coordinate.Plot2, y = Y.Coordinate.Plot2), alpha = 0.1, color = "red") + theme_void()


```

```{r}

# Create a filter to test out different views of the data
# BDC_pass_plot <- BDC_pass_filter %>% filter(game_date == "2/12/2019")
# BDC_pass_plot <- BDC_pass_filter %>% filter(Player.2 == "Hilary Knight")
BDC_pass_plot <- BDC_pass_filter %>% filter(game_date == "2/12/2019", Team == "Olympic (Women) - Canada", Period == 3)

# Prepare the data for plotting
BDC_pass_plot$Team %<>% as.factor()
BDC_pass_plot %<>% 
  select(x = X.Coordinate.Plot, y = Y.Coordinate.Plot, xend = X.Coordinate.Plot2, yend = Y.Coordinate.Plot2, `Passing Strategy`, Team, Clock, Event)


# Create the plot
hockey_plot <- nhl_rink_plot() + 
  geom_link(BDC_pass_plot, mapping = aes(x = x, y = y, xend = xend, yend = yend, colour = `Passing Strategy`, alpha = stat(index), size = stat(index)), lineend = 'round') +
  geom_link(filter(BDC_pass_plot, Event == "Incomplete Play"), mapping = aes(x = x, y = y, xend = xend, yend = yend, alpha = stat(index), size = stat(index)), color = "black", lineend = 'round') +
  scale_size_continuous(range=c(0.1,2)) +
  scale_alpha_continuous(range = c(0.1, 0.3)) + 
  theme_void() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())  +
  theme(
    plot.background = element_rect(fill = "white", colour = "black", size = 1),
    text = element_text(color = "#6F857E", size = 20),
    panel.grid = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = unit(c(10, 2, 10, 2), units = "mm"),
    legend.position="bottom",
    legend.title = element_text(face = "bold"),
    plot.title = element_text(size = 80, face = "bold", family = "Alfa Slab One", color = "#001B2E", lineheight=.3),
    plot.subtitle = element_text(size = 40, family ="Open Sans Condensed", lineheight=.5),
    plot.caption = element_text(lineheight=.2)
  )  +
  labs(
    x = "",
    y = "",
    title = "Passing Strategy",
    subtitle = "North-South vs East-West Strategy",
    caption = "Graphic created by CANA Advisors \n 
               Data sourced from Stathletes Big Data Cup Challenge"
  ) 

# Show the plot in R
hockey_plot


# Change the filename here to save specific versions
ggsave(filename = "hockey_plot.png", 
       plot = hockey_plot, 
       device = "png",
       type = "cairo",
       width = 8, height = 8)
```


